# Security: Require password to access
requirepass trungdeptrai

# Persistence: Enable AOF
appendonly yes
appendfsync everysec

# Memory limit (Avoid crashing VPS/Computer)
maxmemory 256mb
maxmemory-policy noeviction